#!/bin/bash

# Generic vars

# Check if packages where installed
if [ ! -d vendor/bin ]
then
	# If not check if composer exists
	if [ ! $(which composer) ]
	then
		php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
		php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === '41e71d86b40f28e771d4bb662b997f79625196afcca95a5abf44391188c695c6c1456e16154c75a211d238cc3bc5cb47') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
		php composer-setup.php
		php -r "unlink('composer-setup.php');"
		sudo mv composer.phar /usr/local/bin/composer
	fi
	sudo composer install
	sudo chown -R $(whoami) vendor
fi

# Functions
pdepend()
{
	# Create a pdepend report directory
	path="$rdir/pdepend"
	mkdir -p $path

	# Execute scan and output reports
	./vendor/bin/pdepend --summary-xml=$path/summary.xml --jdepend-chart=$path/jdepend.svg --overview-pyramid=$path/pyramid.svg $1
}

phpmd()
{
	# Create a pdepend report directory
	path="$rdir/phpmd"
	mkdir -p $path

	# Execute scan and output reports
	./vendor/bin/phpmd $1 html cleancode,codesize,controversial,design,naming,unusedcode --reportfile $path/phpmd.html --suffixes php,phtml
}

phpcs()
{
	# Create a pdepend report directory
	path="$rdir/phpcs"
	mkdir -p $path

	# Execute scan and output reports
	./vendor/bin/phpcs $1 --report=full --report-file=$path/phpcs.xml
}

phpcpd()
{
	# Create a pdepend report directory
	path="$rdir/phpcpd"
	mkdir -p $path

	# Execute scan and output reports
	./vendor/bin/phpcpd $1 > $path/phpcpd.txt
}

phpdcd()
{
	# Create a pdepend report directory
	path="$rdir/phpdcd"
	mkdir -p $path

	# Execute scan and output reports
	./vendor/bin/phpdcd $1
}

phploc()
{
	# Create a pdepend report directory
	path="$rdir/phploc"
	mkdir -p $path

	# Execute scan and output reports
	./vendor/bin/phploc --log-csv $path/phploc.csv --progress -q > $path/phploc.txt $1
}

phpcbf()
{
	./vendor/bin/phpcbf $1
}

# If project directory exists run all analysers
if [ -d $1 ]
then
	# Report directory
	rdir=reports/$(date +%d%m%Y-%H%M%S)
	mkdir -p $rdir

	# Functions
	pdepend $1 $rdir
	phpmd $1 $rdir
	phpcs $1 $rdir
	phpcpd $1 $rdir
	phpdcd $1 $rdir
	phploc $1 $rdir
#	phpcbf $1$rdir
else
	echo The project\'s path \"$1\" doesn\'t exist
fi
